version: 2.1
jobs:
  test:
    docker:
      - image: hysds/pge-base:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Test
          command: |
            source $HOME/.bash_profile
            pip install moto
            python setup.py install
            pytest .

workflows:
  version: 2
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
            - git-oauth-token
  weekly:
    triggers:
      - schedule:
          cron: "0 7 * * 0"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test:
          context:
            - docker-hub-creds
            - git-oauth-token
          filters:
            branches:
              only: develop

